# Application
server:
  port: 0 # Random port
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: book
    password: book
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Actuator
endpoints:
  info:
    enabled: true # if true then it can be accessed otherwise not
    sensitive: false # if true then need the authorization to show crucial information over HTTP
info:
  app:
    name: Book Services
    description: Spring Cloud Eureka Book Service
    version: 1.0.0

# Eureka
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/