# Application
server:
  port: 8082
spring:
  application:
    name: discovery-service

# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/ # server not to register with another discovery instance.
    register-with-eureka: false
    fetch-registry: false