# Application
server:
  port: 8080
spring:
  application:
    name: gateway-service

# Actuator
endpoints:
  info:
    id: gateway_info # by which this endpoint will be accessed over HTTP
    enabled: true # if true then it can be accessed otherwise not
    sensitive: false # if true then need the authorization to show crucial information over HTTP
info:
  app:
    name: Spring Cloud Eureka Gateway
    description: API Gateway is the single entry point into the microservice ecosystem from the outside world.
    version: 1.0.0

# Zuul
zuul:
  routes:
    discovery-service:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    book-service:
      path: /book-api/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /rating-api/**
      sensitive-headers: Set-Cookie,Authorization
hystrix:
  command:
    discovery-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000