server:
  port: 8080
spring:
  application:
    name: gateway-service

zuul:
  routes:
    discovery-service:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,Authorization
hystrix:
  command:
    discovery-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000