logging:
  config: classpath:config/logback.xml
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: weather
    password: weather
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  messages:
    basename: i18n/messages/messages
    cache-seconds: 3600