logging:
  config: classpath:config/logback.xml
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portal_cnx
    username: postgres
    password: P4ssw0rd
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      idle-timeout: 120000
      maximum-pool-size: 10
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  messages:
    basename: i18n/messages/messages
    cache-seconds: 3600